apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkg-cluster-1
namespace: namespace1000
spec:
  distribution:
    version: v1.16
  topology:
    controlPlane:
      count: 1
      class: guaranteed-small
      storageClass: pacific-gold-storage-policy
    workers:
      count: 2
      class: guaranteed-small
      storageClass: pacific-gold-storage-policy
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]

